name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unit:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [11]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - run: npm install -g @bazel/bazelisk
      - run: bazel build tricky/...
      - run: sbt test
