name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  unit:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: yarn global add @bazel/bazelisk
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: cd multiversion-example && bazel build tricky/...
      - run: sbt test
  checks:
    name: Scalafmt and Scalafix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: yarn global add @bazel/bazelisk
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: sbt scalafmtCheckAll
      - run: sbt 'scalafixAll --check'
